---
- hosts: all
  gather_facts: no

  tasks:
  - name: Update Root user's Password

    user:
      name: lokesh1000
      update_password: always
      password: $6$rounds=656000$xqTG0q3L6Rzv6GeM$aMoR046FW6ADPpjhUK4A.Iec4FF/5hwPGF/tjDl6llvY8pbSwZUh3JzL9xbqJE.l68CXZDhFjR8e0waAz0Wal/

